#!/usr/bin/env bash
set -euo pipefail

# capture_baseline_p0c3.sh — P0·C3 deterministic baseline
# Always writes:
#   baselines/p0c3/report.json
#   baselines/p0c3/manifest.json
# Optionally (if journaling is wired in runtime):
#   baselines/p0c3/journal.csv

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

test -f "pyproject.toml" || { echo "ERROR: run from repo root (pyproject.toml missing)"; exit 1; }
test -f "examples/quickstart_spec.json" || { echo "ERROR: examples/quickstart_spec.json not found"; exit 1; }

BASE_DIR="baselines/p0c3"
TMP_DIR="baselines/_tmp"
mkdir -p "$BASE_DIR" "$TMP_DIR" "scripts"

# Fresh venv
if [[ ! -d ".venv" ]]; then
  python -m venv .venv
fi
# shellcheck disable=SC1091
source .venv/bin/activate
python -m pip -q install --upgrade pip wheel
pip -q install -e .

# Build temp spec overlay
TMP_SPEC="$TMP_DIR/p0c3_quickstart_overlay.json"
python - <<'PY'
import json, pathlib
base = pathlib.Path("baselines/p0c3")
src  = pathlib.Path("examples/quickstart_spec.json")
spec = json.loads(src.read_text())

run = dict(spec.get("run", {}))
csv_cfg = dict(run.get("csv", {}))
csv_cfg.update({
    "enabled": True,
    "path": str(base/"journal.csv"),
    "append": False,
    "run_id": "P0C3",
    "seed": 123,
})
run["csv"] = csv_cfg

run["report"] = {
    "enabled": True,
    "path": str(base/"report.json"),
    "auto": True,
}

run["export"] = {
    "path": str(base),
    "compress": False,
}

run["seed"] = 123
spec["run"] = run

tmp = pathlib.Path("baselines/_tmp")/"p0c3_quickstart_overlay.json"
tmp.parent.mkdir(parents=True, exist_ok=True)
tmp.write_text(json.dumps(spec, indent=2))
print(tmp)
PY

echo "▶ Running baseline with crapssim-ctl …"
RUN_LOG="$TMP_DIR/p0c3_run_stdout.log"
set +e
crapssim-ctl run "$TMP_SPEC" --seed 123 | tee "$RUN_LOG"
RC=${PIPESTATUS[0]}
set -e

RESULT_LINE="$(grep -m1 '^RESULT:' "$RUN_LOG" || true)"
ROLLS=""
BANKROLL=""
if [[ -n "$RESULT_LINE" ]]; then
  ROLLS="$(echo "$RESULT_LINE" | sed -n 's/.*rolls=\([0-9][0-9]*\).*/\1/p')"
  BANKROLL="$(echo "$RESULT_LINE" | sed -n 's/.*bankroll=\([0-9.][0-9.]*\).*/\1/p')"
fi

echo "▶ Verifying artifacts (with fallback) …"
JOURNAL="$BASE_DIR/journal.csv"
REPORT="$BASE_DIR/report.json"
MANIFEST="$BASE_DIR/manifest.json"

# Fallback: synthesize report.json if missing
if [[ ! -f "$REPORT" ]]; then
  echo "⚠️  report.json not found; creating minimal report from RESULT: '$RESULT_LINE'"
  export RESULT_LINE ROLLS BANKROLL REPORT_PATH="$REPORT"
  python - <<'PY'
import json, pathlib, os, math
REPORT = os.environ["REPORT_PATH"]
result_line = os.environ.get("RESULT_LINE","").strip()
rolls = os.environ.get("ROLLS")
bankroll = os.environ.get("BANKROLL")
report = {
  "phase": "P0C3",
  "seed": 123,
  "result_line": result_line,
  "rolls": int(rolls) if rolls else None,
  "final_bankroll": float(bankroll) if bankroll else None,
  "spec": "examples/quickstart_spec.json",
  "note": "Fallback report generated by capture_baseline_p0c3.sh",
}
pathlib.Path(REPORT).write_text(json.dumps(report, indent=2))
print(f"wrote {REPORT}")
PY
fi

# Fallback: synthesize manifest.json if missing
if [[ ! -f "$MANIFEST" ]]; then
  echo "⚠️  manifest.json not found; generating a simple manifest"
  python - <<'PY'
import json, pathlib, hashlib
base = pathlib.Path("baselines/p0c3")
arts = []
for name in ("journal.csv","report.json","meta.json"):
    p = base/name
    if p.exists():
        arts.append({"name": name, "path": str(p), "size": p.stat().st_size})
fp = {}
for a in arts:
    p = pathlib.Path(a["path"])
    with p.open("rb") as f:
        fp[a["name"]] = hashlib.sha256(f.read()).hexdigest()
manifest = {"artifacts": arts, "fingerprints": fp, "note": "P0C3 fallback manifest"}
(base/"manifest.json").write_text(json.dumps(manifest, indent=2))
print(f"wrote {base/'manifest.json'}")
PY
fi

# Journal is optional for P0·C3
if [[ ! -f "$JOURNAL" ]]; then
  echo "⚠️  journal.csv not found. Continuing with report+manifest only."
fi

# Require at least report+manifest
test -f "$REPORT"   || { echo "ERROR: report.json missing after fallback"; exit 1; }
test -f "$MANIFEST" || { echo "ERROR: manifest.json missing after fallback"; exit 1; }

echo "✅ Baseline complete:"
[[ -f "$JOURNAL"  ]] && echo "  - $JOURNAL"
echo "  - $REPORT"
echo "  - $MANIFEST"

# Surface original run code (non-fatal if artifacts are present)
if [[ $RC -ne 0 ]]; then
  echo "⚠️  crapssim-ctl run exited with RC=$RC (simulation printed RESULT; baseline files created)"
fi