name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (engineless)
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip wheel
          # Install this package (editable)
          pip install -e .
          # Ensure engine is NOT present so tests expecting missing engine pass
          pip uninstall -y crapssim || true
          # Test runner
          pip install pytest

      - name: Run tests
        run: |
          . .venv/bin/activate
          pytest -q
