name: P0C1 Verify Lite

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      SPEC_PATH: examples/quickstart_spec.json
      SEED: "123"
      ROLLS: "50"
      PYTHONUNBUFFERED: "1"
      PYTHONHASHSEED: "0"
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Repo & spec check
        run: ls -la && (ls -la examples || true) && (ls -la crapssim_control || true) && [ -f "$SPEC_PATH" ] || (echo "Spec not found: $SPEC_PATH" && exit 1)

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install engine & package
        run: python -m pip install -U pip && pip install crapssim PyYAML && pip install -e . && python -c "import importlib.metadata as m; print('crapssim=='+m.version('crapssim'))"

      - name: Run (plain)
        run: python -c "from crapssim_control.cli import main; import sys,os; sys.exit(main(['run', os.environ['SPEC_PATH'], '--seed', os.environ['SEED'], '--rolls', os.environ['ROLLS']]))"

      - name: Run (flags) and compare to plain
        run: sh -lc "python -c 'from crapssim_control.cli import main; import sys,os; sys.exit(main([\"run\", os.environ[\"SPEC_PATH\"], \"--seed\", os.environ[\"SEED\"], \"--rolls\", os.environ[\"ROLLS\"]]))' > out_plain.txt 2>&1 || true; python -c 'from crapssim_control.cli import main; import sys,os; sys.exit(main([\"run\", os.environ[\"SPEC_PATH\"], \"--seed\", os.environ[\"SEED\"], \"--rolls\", os.environ[\"ROLLS\"], \"--demo-fallbacks\", \"--strict\", \"--no-embed-analytics\"]))' > out_flags.txt 2>&1 || true; diff -u out_plain.txt out_flags.txt"