name: P0C1 – Verify

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      SPEC_PATH: examples/quickstart_spec.json
      SEED: "123"
      ROLLS: "50"
      PYTHONUNBUFFERED: "1"
      PYTHONHASHSEED: "0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show repo & spec
        run: ls -la && ls -la examples || true && ls -la crapssim_control || true && test -f "$SPEC_PATH" || (echo "Spec not found: $SPEC_PATH" && exit 1)

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install engine & package
        run: python -m pip install -U pip && pip install "crapssim" "PyYAML>=6.0" && pip install -e . && python -c "import importlib.metadata as m; print('crapssim=='+m.version('crapssim'))"

      # run once plain
      - name: Run (plain)
        run: python -c "from crapssim_control.cli import main; import sys; sys.exit(main(['run','${{ env.SPEC_PATH }}','--seed','${{ env.SEED }}','--rolls','${{ env.ROLLS }}']))"

      # run again with flags; must be identical (inert flags)
      - name: Run (with flags)
        run: |
          python -c "from crapssim_control.cli import main; import sys; sys.exit(main(['run','${{ env.SPEC_PATH }}','--seed','${{ env.SEED }}','--rolls','${{ env.ROLLS }}','--demo-fallbacks','--strict','--no-embed-analytics']))"